name: Java CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 21
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Build with Maven
        run: mvn clean install

      - name: Create Report directory
        run: mkdir -p Reports

      - name: Run tests with Maven
        run: mvn test

      - name: List files in the project directory
        run: ls -R

      - name: List files in the Report directory
        run: ls -R Reports

      - name: Archive test reports
        if: always()
        uses: actions/upload-artifact@v2
        with:
          path: Reports/*.html