name: Java CI with TestNG

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 21
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Run tests with TestNG and generate report
        run: mvn clean test -Dtestng.dtd.http=true

      - name: Archive test reports
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: SauceDemo Reports
          path: target/*.html